// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-images.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var BACKEND_BASE_URL = "https://pixel-vault-backend-tqww.onrender.com/api";
var search_images_default = defineTool({
  name: "search_public_images",
  title: "Search public images",
  description: "Search the PixelVault public image library by keyword, title, or description. Returns image metadata including URL, dimensions, and keywords.",
  inputSchema: {
    searchText: z.string().default("").describe("Text to search for. Leave empty to browse recent public images."),
    limit: z.number().int().min(1).max(50).default(12).describe("Maximum number of images to return (1-50)."),
    offset: z.number().int().min(0).default(0).describe("Pagination offset.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ searchText, limit, offset }) => {
    try {
      const res = await fetch(`${BACKEND_BASE_URL}/image/search`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ searchText, limit, offset, myLibrary: false })
      });
      if (!res.ok) {
        return {
          content: [{ type: "text", text: `Search failed: ${res.status} ${res.statusText}` }],
          isError: true
        };
      }
      const data = await res.json();
      const items = (data?.data ?? []).map((img) => ({
        id: img.id,
        title: img.title,
        description: img.description,
        image_url: img.image_url,
        width: img.width,
        height: img.height,
        keywords: img.keywords
      }));
      return {
        content: [
          {
            type: "text",
            text: `Found ${data?.totalCount ?? items.length} image(s). Showing ${items.length}.`
          }
        ],
        structuredContent: {
          totalCount: data?.totalCount ?? items.length,
          publicCount: data?.publicCount,
          items
        }
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Error: ${err.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/get-image.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var BACKEND_BASE_URL2 = "https://pixel-vault-backend-tqww.onrender.com/api";
var get_image_default = defineTool2({
  name: "get_public_image",
  title: "Get public image by ID",
  description: "Fetch a single public PixelVault image's metadata by its ID.",
  inputSchema: {
    id: z2.string().min(1).describe("The image ID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ id }) => {
    try {
      const res = await fetch(`${BACKEND_BASE_URL2}/image/search`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ searchText: id, limit: 1, offset: 0, myLibrary: false })
      });
      if (!res.ok) {
        return {
          content: [{ type: "text", text: `Lookup failed: ${res.status}` }],
          isError: true
        };
      }
      const data = await res.json();
      const img = (data?.data ?? []).find((i) => i.id === id) ?? data?.data?.[0];
      if (!img) {
        return { content: [{ type: "text", text: "Image not found." }], isError: true };
      }
      return {
        content: [{ type: "text", text: JSON.stringify(img, null, 2) }],
        structuredContent: { image: img }
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Error: ${err.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "pixelvault-mcp",
  title: "PixelVault MCP",
  version: "0.1.0",
  instructions: "Tools for browsing the PixelVault public image library. Use `search_public_images` to find images by text, and `get_public_image` to fetch a specific image's metadata.",
  tools: [search_images_default, get_image_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
